#batch_size: [64, 64, 64]
#random_reverse: [True, False]
dim_embedding: [16, 32, 64, 128]
dim_embedding_tissue: [4, 8, 16, 32]

predictor_hidden: [32, 64, 128]
predictor_dropout: [0.0, 0.1, 0.3]

lr:
  min: 1e-5
  max: 1e-2
weight_decay:
  min: 1e-5
  max: 1e-3

lr_scheduler_enable: [True, False]
reset_epochs: [5, 10, 20]
T_mult: [1, 2, 3]