num_layers: [6, 7, 8, 9]
dropout: [0.0, 0.1, 0.3]

align_aug: [True, False]
concat_tissue_feature: [True, False]
frequency_features: [True, False]
seq_only: [True, False]
seq_encoding: ["embedding", "ohe"]

grad_clip_norm:
  min: 0.1
  max: 5.0