subproject: "dev_baseline/delete_me"
#subproject: "dev_baseline/v1_codon_full_data_replica_tissue12"
#subproject: "bin/dev_baseline/codon_freq_v1"

# Training
epochs: 2
save_freq: 10
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1

# Model
model: "baseline"
dim_embedding_tissue: 16  # max 29 tissues
dim_embedding_token: 32  # 64 codons or 4 nucleotides

hidden_size: 256
dropout: 0.2

# Optimizer
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.1  # ranger only
