# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1


# FOR CODON DATA
# Model
model: "baseline"
dim_embedding_tissue: 128  # max 29 tissues
dim_embedding_token: 128  # 64 codons or 4 nucleotides
random_reverse: True

hidden_size: 512
dropout: 0.4

# Optimizer
optimizer:
  name: adam
  lr: 0.00032143048707089674
  weight_decay: 0


# FOR FREQUENCY DATA
## Model
# #EPOCHS: 150
#model: "baseline"
#dim_embedding_tissue: 64  # max 29 tissues
#dim_embedding_token: 64  # 64 codons or 4 nucleotides
#random_reverse: True
#
#hidden_size: 512
#dropout: 0.0
#
## Optimizer
#optimizer:
#  name: adam
#  lr: 0.0006018234365492453
#  weight_decay: 0