# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1


# FOR CODON DATA
# Model
model: "baseline"
dim_embedding_tissue: 64  # max 29 tissues
dim_embedding_token: 64  # 64 codons or 4 nucleotides

hidden_size: 256
dropout: 0.1

# Optimizer
optimizer:
  name: adam
  lr: 0.001


# FOR FREQUENCY DATA
# Model
#model: "baseline"
#dim_embedding_tissue: 16  # max 29 tissues
#dim_embedding_token: 16  # 64 codons or 4 nucleotides
#
#hidden_size: 512
#dropout: 0.5
#
## Optimizer
#optimizer:
#  name: adam
#  lr: 0.01