#subproject: "dev_baseline/v3_full_seq_length_200"
subproject: "dev_baseline/delete_me"

# Training
epochs: 100
save_freq: 25
val_freq: 10
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "baseline"
dim_embedding_tissue: 16  # max 29 tissues
dim_embedding_token: 32  # 64 codons or 4 nucleotides/
hidden_size: 1024

# Optimizer
optimizer:
  name: adam
  lr: 0.001
