# Training
epochs: 100
save_freq: 5
val_freq: 1
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "cnn"
dim_embedding_tissue: 16  # max 29 tissues
dim_embedding_token: 32  # 64 codons or 4 nucleotides
predictor_hidden_dim: 64
predictor_dropout: 0.1

# Convolutional Layer Parameters
numFiltersConv1: 128
filterLenConv1: 6
dilRate1: 1
maxPool1: 30

numFiltersConv2: 32
filterLenConv2: 9
dilRate2: 1
maxPool2: 10


# Optimizer
optimizer:
  name: adam  # sgd, adam, ranger
  lr: 0.001
  momentum: 0.9  # sgd only
  weight_decay: 0.1  # ranger only