# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1

# Model
model: "cnn"
dim_embedding_tissue: 128  # max 29 tissues
dim_embedding_token: 128  # 64 codons or 4 nucleotides
predictor_hidden_dim: 128
predictor_dropout: 0.1
random_reverse: True

# Convolutional Layer Parameters
num_kernels_conv1: 64
kernel_size_conv1: 6
stride_conv1: 1
max_pool1: 20

num_kernels_conv2: 32
kernel_size_conv2: 9
stride_conv2: 1
max_pool2: 5

padding: 'same' # only supports same currently

# Optimizer
optimizer:
  name: adam
  lr: 0.0009882333318255191
  weight_decay: 0