subproject: "dev"
project_path: ""  # optional, project path with data and model weights
log_file_path: "" # optional

folding_algorithm: "viennarna" # viennarna, linearfold  # TODO allow for data augmentation, by using different folding algorithms?
nr_folds: 5
seed: 2024

model: "dummy" # dummy, baseline, lstm, xlstm, mamba, transformer, best
epochs: 4
save_freq: 2
val_freq: 2
warmup: 0

batch_size: 32
num_workers: 1

optimizer:
  name: adam
  lr: 0.001
  momentum: 0.9
