subproject: "dev_dummy/dummy"

# Training
epochs: 6
save_freq: 3
val_freq: 3
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "dummy" # dummy, baseline, gru, lstm, xlstm, mamba, transformer, best

# Optimizer
optimizer:
  name: adam
  lr: 0.001
