# General
seed: 2024
gpu_id: 0
dev: True

# Data files
#train_data_file: "train_9.0k_data.pkl"
#val_data_file: "val_9.0k_data.pkl"
#test_data_file: "test_9.0k_data.pkl"
train_data_file: "dev_train_9.0k_data.pkl"
val_data_file: "dev_val_9.0k_data.pkl"
test_data_file: "dev_test_9.0k_data.pkl"
pretrain_path: ""  # TODO implement (latest?)

# Data params
max_seq_length: 9000
binary_class: True
frequency_features: False
random_reverse: True
tissue_id: -1  # 0-28 or -1 for all tissues

# Misc
nr_folds: 1  # only 1 supported, as cross validation only for codon based models supported
val_fraction_of_train: 0  # use val_data_file as validation set
embedding_max_norm: 2

early_stopper_patience: 8  # disabled if < 0
early_stopper_delta: 0.01

final_evaluation: True  # if True, will evaluate the model on the train val set after training
clean_up_weights: True  # if True, will remove the non-optimal model weights after training

# Paths
project_path: ""  # optional, project path with data and model weights
log_file_path: "" # optional
