# General
seed: 2024
gpu_id: 1
dev: True
tissue_id: -1  # 0-28 or -1 for all tissues

# Data
#train_data_file: "train_8.1k_data.pkl"
train_data_file: "dev_train_8.1k_data.pkl"
test_data_file: "test_8.1k_data.pkl"
max_seq_length: 2700
binary_class: True
frequency_features: True
random_reverse: True

# Misc
nr_folds: 1  # if 1, will take 20% of the train data as validation set during training ("train val")
val_fraction: 0.15  # only if nr_folds == 1
embedding_max_norm: 2

early_stopper_patience: 6  # disabled if < 0
early_stopper_delta: 0.01

final_evaluation: True  # if True, will evaluate the model on the train val set after training
clean_up_weights: True  # if True, will remove the non-optimal model weights after training

# Paths
project_path: ""  # optional, project path with data and model weights
log_file_path: "" # optional