# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1

# Model
model: "gru"
dim_embedding_tissue: 128  # max 29 tissues
dim_embedding_token: 128  # 64 codons or 4 nucleotides
predictor_hidden_dim: 64
predictor_dropout: 0.1
random_reverse: True

bidirectional: True
rnn_hidden_size: 256
num_layers: 2
dropout: 0.1

# Optimizer
optimizer:
  name: adam
  lr: 1.3196675488432542e-05
  weight_decay: 0
