#subproject: "dev_gru/v2_test_100"
subproject: "dev_gru/delete_me"

# Training
gpu_id: 0
epochs: 100
save_freq: 25
val_freq: 10
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "gru"
dim_embedding_token: 32  # 64 codons or 4 nucleotides
predictor_hidden_dim: 64
predictor_dropout: 0.1

dropout: 0.3
bidirectional: False
rnn_hidden_size: 512
num_layers: 2

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.1  # ranger only
