# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1

# Model
model: "gru"
dim_embedding_tissue: 64  # max 29 tissues
dim_embedding_token: 64  # 64 codons or 4 nucleotides
predictor_hidden_dim: 64
predictor_dropout: 0.1

bidirectional: True
rnn_hidden_size: 512
num_layers: 3
dropout: 0.0

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0
