# FIXME Cuda out of memory error!

#subproject: "dev_jamba/test_150"
subproject: "dev_jamba/delete_me"

# Training
gpu_id: 0
epochs: 150
save_freq: 25
val_freq: 10
warmup: 0
batch_size: 16
num_workers: 1

# Model
model: "jamba"
dim_embedding_token: 64  # Embedding dimension for tokens
tissue_embedding_dim: 32  # Embedding dimension for tissues
out_hidden_size: 64

# Jamba parameters
depth: 1
d_state: 256
d_conv: 128  # output_dim
heads: 4
num_experts: 4
num_experts_per_token: 2

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
