# Paths
subproject: "dev_lstm/v2_test_150"
train_data_file: "dev_train_data_1000_full_length.pkl" # dev_train_data_1000.pkl or dev_train_data_1000_full_length.pkl
project_path: ""  # optional, project path with data and model weights
log_file_path: "" # optional

# General
folding_algorithm: "viennarna" # viennarna, linearfold  # TODO allow for data augmentation, by using different folding algorithms?
nr_folds: 1  # if 1, will take 20% of the data as validation set
gpu_id: 0
seed: 2024
max_seq_length: 3000  # later to 2700

# Training
epochs: 150
save_freq: 25
val_freq: 10
warmup: 0
batch_size: 32
num_workers: 1
final_evaluation: True
clean_up_weights: True

# Model
model: "lstm"
dim_embedding_token: 32  # 64 codons or 4 nucleotides
dropout: 0.3
bidirectional: False
rnn_hidden_size: 512
out_hidden_size: 64
num_layers: 2


# Optimizer
optimizer:
  name: adam
  lr: 0.0001
