#subproject: "dev_lstm/v2_test_150"
subproject: "dev_lstm/delete_me"

# Training
gpu_id: 0
epochs: 150
save_freq: 25
val_freq: 10
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "lstm"
dim_embedding_token: 32
dropout: 0.3
bidirectional: False
rnn_hidden_size: 512
out_hidden_size: 64
num_layers: 2

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.1  # ranger only
