# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 64
num_workers: 1

# Model
model: "RiboNN"
dim_embedding_tissue: 128
dim_embedding_token: 128
predictor_hidden_dim: 32  # hidden size of predictor network
predictor_dropout: 0.1  # dropout of predictor network
grad_clip_norm: 0.2745393751090204
random_reverse: True

num_layers: 4  # number of layers in the model, more than 8 not possible for seq len 2700
dropout: 0.1  # dropout rate of the model

# Optimizer
optimizer:
  name: adam  # sgd, adam, ranger
  lr: 0.0018021153781358553
  weight_decay: 0