# Training
epochs: 6
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "template"
dim_embedding_tissue: 8  # max 29 tissues
dim_embedding_token: 8  # 64 codons or 4 nucleotides/
predictor_hidden_dim: 64  # hidden size of the output layer
predictor_dropout: 0.1  # dropout rate of the output layer

# add model specific parameters here


# Optimizer
optimizer:
  name: adam  # sgd, adam, ranger
  lr: 0.001
  momentum: 0.9  # sgd only
  weight_decay: 0  # ranger only