subproject: "dev/run"

# Training
gpu_id: 0
epochs: 6
save_freq: 3
val_freq: 3
warmup: 0
batch_size: 32
num_workers: 1

# Model
model: "template"
dim_embedding_tissue: 16  # max 29 tissues
dim_embedding_token: 32  # 64 codons or 4 nucleotides/
out_hidden_size: 64  # hidden size of the output layer
# add model specific parameters here

# Optimizer
optimizer:
  name: adam  # adam or sgd
  lr: 0.001
  momentum: 0.9  # only for sgd