#subproject: "xlstm/v1_codon_full_data"
subproject: "dev_xlstm/delete_me"

# Training
gpu_id: 0
epochs: 50
save_freq: 10
val_freq: 10
warmup: 0
batch_size: 16
num_workers: 1

# Model
model: "xlstm"
dim_embedding_token: 32
tissue_embedding_dim: 32
out_hidden_size: 64

# xLSTM Config
conv1d_kernel_size: 4
qkv_proj_blocksize: 4
num_heads: 4
proj_factor: 1.3
act_fn: "gelu"
num_blocks: 7
slstm_at: [1]
bias: True
dropout: 0.1

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.1  # ranger only
