# Currently only works on gpu 0!

# Training
epochs: 100
save_freq: 1
val_freq: 1
warmup: 0
batch_size: 16
num_workers: 1

# Model
model: "xlstm"
dim_embedding_tissue: 64  # max 29 tissues
dim_embedding_token: 64  # 64 codons or 4 nucleotides
predictor_hidden_dim: 64
predictor_dropout: 0.1
random_reverse: False

# xLSTM Config
conv1d_kernel_size: 9
num_heads: 8  # for both s and mLSTM

m_qkv_proj_blocksize: 8
s_proj_factor: 1
s_act_fn: "gelu"

num_blocks: 5
slstm_at: "all"  # define block position of sLSTM
bias: True
dropout: 0.4

# Optimizer
optimizer:
  name: adam
  lr: 0.00029630029586396017
  weight_decay: 0
