# Paths
subproject: "dev_xlstm/v2_test_150"
#subproject: "dev_xlstm/delete_me"
train_data_file: "dev_train_data_1000_full_length.pkl" # dev_train_data_1000.pkl or dev_train_data_1000_full_length.pkl
project_path: ""  # optional, project path with data and model weights
log_file_path: "" # optional

# General
folding_algorithm: "viennarna"  # options: viennarna, linearfold
nr_folds: 1  # if 1, will take 20% of the data as validation set
gpu_id: 0
seed: 2024
max_seq_length: 3000  # Should match context_length in xLSTMBlockStack

# Training
epochs: 150
save_freq: 10
val_freq: 5
warmup: 0
batch_size: 32
num_workers: 1
final_evaluation: True
clean_up_weights: False

# Model
model: "xlstm"
dim_embedding_token: 32  # Embedding dimension for tokens
tissue_embedding_dim: 32  # Embedding dimension for tissues
out_hidden_size: 64
output: 1

# xLSTM Config
conv1d_kernel_size: 4
qkv_proj_blocksize: 4
num_heads: 4
proj_factor: 1.3
act_fn: "gelu"
num_blocks: 7
slstm_at: [1]
bias: True
dropout: 0.1

# Optimizer
optimizer:
  name: adam
  lr: 0.0001
